### ISSUE TITLE
Swift 4 / Xcode 9.1 Warnings

### ISSUE THREAD

**Issue by Pencl** [scarabresearch/EmarsysPredictSDKiOS#1]
In Xcode 9 there are tons of warnings when compiling due to deprecations.

<img width="1027" alt="bildschirmfoto 2017-11-09 um 10 01 20" src="https://user-images.githubusercontent.com/7498051/32596966-720226a4-c535-11e7-8681-442cb1997cd9.png">

**Comment by lucasecf** [comment]
What's more annoying is that these warnings apparently cannot be ignored by a `inhibit_all_warnings!` in the Podfile...

**Comment by Pencl** [comment]
I issued an official bug report at Emarsys a few weeks ago - but no reaction so far.

**Comment by andrascsibi** [comment]
Hi @Pencl @lucasecf ,

Sorry for the late reply, I didn't realize that these deprecation warnings break your build. We'll look into these warnings, and send you an update before the Holidays kick in.

BR,
Andras

**Comment by andrascsibi** [comment]
Hi @Pencl @lucasecf ,

After looking into the issue, we discovered that the deprecation warnings do not actually break the build, although they are undeniably ugly. Are there any negative effects of the warnings apart from being a nuisance in your IDE? 

BR,
Andras

**Comment by lucasecf** [comment]
@andrascsibi No, they are "just" warnings and it doesn't affect the build anyhow. But although we do have a big project with more than 2 years old, we have zero tolerance for warnings. The only ones we have right now are the ones given by this emarsys SDK. 

Usually we just ignore warnings in dependencies code, since we cannot control them. But like I said before, unfortunately neither `inhibit_all_warnings!` nor `:inhibit_warnings => true` in the Podfile works for ignoring this ones "provided" by emarsys SDK.

If you know any other way to ignore them instead of just "fixing" them, would love to try

**Comment by andrascsibi** [comment]
Hi @lucasecf @Pencl ,

Our mobile SDK team has looked at the issue, but couldn't find an obvious quick fix right away. This would require a more detailed analysis. Unfortunately they are quite busy working with other SDK-s, so they can only undertake this project in Q2 the earliest. 

I'm leaving this issue open for until then. Thanks for your patience.

BR,
Andras

**Comment by Hozeee** [comment]
Hello @lucasecf @Pencl,

We've fixed this issue, and release a new version of SDK.

Thanks for your patience!

BR,
Joco

**Comment by nikolaminov** [comment]
Hi @Hozeee @andrascsibi, 
Even though the issue is fixed we cannot use it because you did not make a new release. Also, since there is no static podspec file in the repo, we cannot point to the master branch or to the specific commit. 
Do you have plans to make a new version release soon or is there another way to use this?

**Comment by Hozeee** [comment]
Hello @nikolaminov!

Sorry, it was my fault, i've recently released a new version to Cocoapods!
